services:
  - type: web
    name: collabboard-server
    runtime: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd server && npm install && npm start
    envVars:
      - key: NODE_ENV
        value: production
